puts "The students of my cohort at Makers Academy"
puts "------------"
puts "Jin Dai"
puts "Huy Le"
puts "Sanda Golcea"
puts "Emily Sas"
puts "Matteo Manzo"
puts "Hannah Carney"
puts "Gus Powell"
puts "Charlie Walsh"
puts "Oliver Lucas"

print "Overall, we have "
print 9
print " great students"